apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pocketbase.fullname" . }}
  labels:
    {{- include "pocketbase.labels" . | nindent 4 }}
    {{- if .Values.epinio }}
    epinio.io/configuration: "true"
    epinio.io/configuration-origin: {{ .Values.epinio.serviceName }}
    epinio.io/configuration-type: service
    {{- end }}
data:
  {{- if .Release.IsInstall }}
  {{ $pbAdminPassword := default (randAlphaNum 32) .Values.superuserInitialPassword }}
  PB_HOST: {{ printf "%s.%s.%s" (include "pocketbase.fullname" .) .Release.Namespace  .Values.domain  | b64enc }}
  PB_UI: {{ printf "%s.%s.%s/_/" (include "pocketbase.fullname" .) .Release.Namespace  .Values.domain  | b64enc }}
  PB_API: {{ printf "%s.%s.%s/api/" (include "pocketbase.fullname" .) .Release.Namespace  .Values.domain  | b64enc }}
  PB_ADMIN_EMAIL: {{ .Values.superuserEmail | b64enc }}
  PB_ADMIN_PASSWORD: {{ $pbAdminPassword | b64enc }}
  {{ else }}
  PB_HOST: {{ ((lookup "v1" "Secret" .Release.Namespace (include "pocketbase.fullname" .)).data).PB_HOST }}
  PB_UI: {{ ((lookup "v1" "Secret" .Release.Namespace (include "pocketbase.fullname" .)).data).PB_UI }}
  PB_API: {{ ((lookup "v1" "Secret" .Release.Namespace (include "pocketbase.fullname" .)).data).PB_API }}
  PB_ADMIN_EMAIL: {{ ((lookup "v1" "Secret" .Release.Namespace (include "pocketbase.fullname" .)).data).PB_ADMIN_EMAIL }}
  PB_ADMIN_PASSWORD: {{ ((lookup "v1" "Secret" .Release.Namespace (include "pocketbase.fullname" .)).data).PB_ADMIN_PASSWORD }}
  {{ end }}

