apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: "{{ include "grafana.fullname" . }}-default-folder"
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  instanceSelector:
    matchLabels:
      {{- include "grafana.labels" . | nindent 6 }}
  title: Default
