apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "grafana.fullname" . }}-grafana-operator-auth"
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  {{- if .Release.IsInstall }}
  username: {{ default (include "grafana.fullname" .) .Values.grafana.username | b64enc }}
  password: {{ default (randAlphaNum 32) .Values.grafana.password | b64enc }}
  {{ else }}
  username:  {{ ((lookup "v1" "Secret" .Release.Namespace ( printf "%s-grafana-operator-auth" (include "grafana.fullname" .))).data).username }}
  password: {{ ((lookup "v1" "Secret" .Release.Namespace ( printf "%s-grafana-operator-auth" (include "grafana.fullname" .))).data).password }}
  {{ end }}
