apiVersion: v1
kind: Secret
metadata:
  name: "{{ printf "%s-grafana-prometheus-proxy" .Release.Name }}"
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  {{- if .Release.IsInstall }}
  {{ $prometheusPassword := default (randAlphaNum 32) .Values.grafana.PROMETHEUS_PASSWORD }}
  PROMETHEUS_PASSWORD: {{ $prometheusPassword | b64enc }}
  authn: {{ fromJson (printf "{\"users\":[{\"username\":\"%s\",\"password\":\"%s\",\"namespaces\":[\"%s\"]}]}" 
  (printf "%s-grafana-prometheus-proxy" .Release.Name) $prometheusPassword .Release.Namespace) | toYaml | b64enc }}
  {{ else }}
  PROMETHEUS_PASSWORD: {{ ((lookup "v1" "Secret" .Release.Namespace (printf "%s-grafana-prometheus-proxy" .Release.Name)).data).PROMETHEUS_PASSWORD }}
  authn: {{ ((lookup "v1" "Secret" .Release.Namespace (printf "%s-grafana-prometheus-proxy" .Release.Name)).data).authn }}
  {{ end }}
