apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    {{- if .Values.epinio }}
    epinio.io/configuration: "true"
    epinio.io/configuration-origin: {{ .Values.epinio.serviceName }}
    epinio.io/configuration-type: service
    {{- end }}
data:
  {{- if .Release.IsInstall }}
  host: {{ printf "%s.%s.%s" (include "grafana.fullname" .) .Release.Namespace  .Values.grafana.domain  | b64enc }}
  username: {{ default (include "grafana.fullname" .) .Values.grafana.username | b64enc }}
  password: {{ default (randAlphaNum 32) .Values.grafana.password | b64enc }}
  {{ else }}
  host: {{ index (lookup "v1" "Secret" .Release.Namespace (include "grafana.fullname" .)).data "host" }}
  username:  {{ index (lookup "v1" "Secret" .Release.Namespace (include "grafana.fullname" .)).data "username" }}
  password: {{ index (lookup "v1" "Secret" .Release.Namespace (include "grafana.fullname" .)).data "password" }}
  {{ end }}
