{{- if not .Values.certManager.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  annotations:
  name: epinio-registry-tls
  namespace: {{ .Release.Namespace }}
stringData:
  ca.crt: {{ .Values.certManager.registry.ca | quote }}
  tls.key: {{ .Values.certManager.registry.key | quote }}
  tls.crt: {{ .Values.certManager.registry.cert | quote }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  annotations:
  name: epinio-tls
  namespace: {{ .Release.Namespace }}
stringData:
  ca.crt: {{ .Values.certManager.epinio.ca | quote }}
  tls.key: {{ .Values.certManager.epinio.key | quote }}
  tls.crt: {{ .Values.certManager.epinio.cert | quote }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  annotations:
  name: dex-tls
  namespace: {{ .Release.Namespace }}
stringData:
  ca.crt:  {{ .Values.certManager.dex.ca   | default .Values.certManager.epinio.ca   | quote }}
  tls.key: {{ .Values.certManager.dex.key  | default .Values.certManager.epinio.key  | quote }}
  tls.crt: {{ .Values.certManager.dex.cert | default .Values.certManager.epinio.cert | quote }}
{{- end }}
{{- if and .Values.epinioUI.enabled .Values.epinioUI.ingress.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  annotations:
  name: epinio-ui-tls
  namespace: {{ .Release.Namespace }}
stringData:
  ca.crt:  {{ .Values.certManager.ui.ca   | default .Values.certManager.epinio.ca   | quote }}
  tls.key: {{ .Values.certManager.ui.key  | default .Values.certManager.epinio.key  | quote }}
  tls.crt: {{ .Values.certManager.ui.cert | default .Values.certManager.epinio.cert | quote }}
{{- end }}
{{- if .Values.minio.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  annotations:
  name: minio-tls
  namespace: {{ .Release.Namespace }}
stringData:
  ca.crt: {{ .Values.certManager.s3.ca | quote }}
  tls.key: {{ .Values.certManager.s3.key | quote }}
  tls.crt: {{ .Values.certManager.s3.cert | quote }}
{{- else if .Values.s3gw.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  annotations:
  name: s3gw-cluster-ip-tls
  namespace: {{ .Release.Namespace }}
stringData:
  ca.crt: {{ .Values.certManager.s3.ca | quote }}
  tls.key: {{ .Values.certManager.s3.key | quote }}
  tls.crt: {{ .Values.certManager.s3.cert | quote }}
{{- end }}
{{- end }}
