apiVersion: v1
kind: Secret
type: BasicAuth
metadata:
  labels:
    epinio.io/api-user-credentials: "true"
    epinio.io/role: "admin"
  name: admin-epinio-user
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.api.username }}
  password: {{ .Values.api.password }}
---
apiVersion: v1
kind: Secret
type: BasicAuth
metadata:
  labels:
    epinio.io/api-user-credentials: "true"
    epinio.io/role: "user"
  name: default-epinio-user
  namespace: {{ .Release.Namespace }}
stringData:
  username: epinio
  password: password
  namespaces: |
    workspace
