# https://github.com/tektoncd/catalog/blob/main/task/aws-cli/0.2/aws-cli.yaml
# Also look at [1]
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: aws-cli
  namespace: tekton-staging
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/categories: CLI
    tekton.dev/tags: cli
    tekton.dev/displayName: "aws cli"
spec:
  description: >-
    This task performs operations on Amazon Web Services resources using aws.

  workspaces:
    - name: source
      optional: true
    - name: secrets
      optional: true
      #  [1] https://github.com/tektoncd/pipeline/issues/2013
      mountPath: /root/.aws
  params:
    - name: SCRIPT
      description: The AWS script to run
      type: string
      default: "aws $@"
    - name: ARGS
      description: AWS cli arguments to be passed
      type: array
      default: ["help"]
  steps:
    - name: awscli
      image: "{{ template "registry-url" . }}{{ .Values.tekton.awsCliImage }}"
      script: "$(params.SCRIPT)"
      args:
        - "$(params.ARGS)"
