apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "apm.fullname" . }}-oauth2"
  labels:
    {{- include "apm.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
    app.kubernetes.io/oauth2-proxy: true
data:
  OAUTH2_PROXY_CLIENT_ID: "{{ .Values.keycloak.clientId | b64enc }}"
  OAUTH2_PROXY_CLIENT_SECRET: "{{ .Values.keycloak.clientSecret | b64enc }}"
  OAUTH2_PROXY_COOKIE_SECRET: "{{ .Values.keycloak.cookieSecret | b64enc }}"
