epinio: {}

grafana:
  domain: domain.tld
  persistentVolumeClaim:
    enabled: true
  ingress:
    ingressClassName: nginx
    annotations: {}
  keycloak:
    enabled: true
    endpoint: http://localhost
    realm: realm_name
    client_id: client_id
    client_secret: client_secret

global:
  prometheus:
    url: http://prometheus.domain.tld
  loki:
    url: http://loki.domain.tld

prometheus-multi-tenant-proxy:
  proxy:
    extraEnv:
    - name: PROM_PROXY_PROTECTED_ENDPOINTS
      value: ""
