{{ $secretName := .Values.epinio.serviceName | default .Release.Name }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.name }}
    kind: {{ .Values.externalSecrets.kind }}
  target:
    name: {{ printf "%s-external-secret" (include "vault.fullname" .) }}
  dataFrom:
  - extract:
      key: {{ printf "%s/%s" .Release.Namespace $secretName }}
