{{ $secretName := .Values.epinio.serviceName | default .Release.Name }}
apiVersion: kv.vault.upbound.io/v1alpha1
kind: SecretV2
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
spec:
  forProvider:
    cas: 1
    customMetadata:
      - deleteVersionAfter: 6000
        maxVersions: 99
    mount: {{ .Values.vault.mount | quote }}
    name: {{ printf "%s/%s" .Release.Namespace $secretName }}
    disableRead: true
    dataJsonSecretRef:
      key: values
      name: {{ include "vault.fullname" . }}
      namespace: {{ .Release.Namespace }}
  providerConfigRef:
    name: {{ .Values.vault.provider | quote }}
