apiVersion: kv.vault.upbound.io/v1alpha1
kind: SecretV2
metadata:
  name: {{ .Release.Name }}
spec:
  forProvider:
    cas: 1
    customMetadata:
      - deleteVersionAfter: 6000
        maxVersions: 99
    mount: {{ .Values.vault.mount | quote }}
    name: {{ printf "%s/%s" .Release.Namespace .Release.Name }}
    disableRead: true
    dataJsonSecretRef:
      key: values
      name: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
  providerConfigRef:
    name: {{ .Values.vault.provider | quote }}
