{{ $secretName := .Values.epinio.serviceName | default .Release.Name }}
apiVersion: kv.vault.upbound.io/v1alpha1
kind: SecretV2
metadata:
  name: {{ printf "%s-%s" .Release.Namespace (include "vault.fullname" .) }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
spec:
  # Requires managementPolicy feature flag to be enabled on the provider config
  # Use a DeploymentRuntimeConfig to do so
  managementPolicies: ["Create", "Delete", "Observe"]
  forProvider:
    deleteAllVersions: true
    customMetadata:
      - maxVersions: 99
    mount: {{ .Values.vault.mount | quote }}
    name: {{ printf "%s/%s" .Release.Namespace $secretName }}
    disableRead: true
    dataJsonSecretRef:
      key: values
      name: {{ include "vault.fullname" . }}
      namespace: {{ .Release.Namespace }}
  providerConfigRef:
    name: {{ .Values.vault.provider | quote }}
