apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- if .Values.epinio }}
    epinio.io/configuration: "true"
    epinio.io/configuration-origin: {{ .Values.epinio.serviceName }}
    epinio.io/configuration-type: service
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  values: |
    {}
