apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.commonLabels }}
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  values: |
    {}
