{{- $serviceName := include "pulumi-stack.serviceName" .}}
---
apiVersion: batch/v1
kind: Job
metadata: 
  name: "{{ include "pulumi-stack.fullname" . }}-wait-stack"
  namespace: pulumi-operator
  labels:
    {{- include "pulumi-stack.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
spec:
  template:
    metadata:
      name: "{{ include "pulumi-stack.fullname" . }}-wait-stack"
      namespace: pulumi-operator
      labels:
        {{- include "pulumi-stack.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: "{{ include "pulumi-stack.fullname" . }}-wait-stack"
      containers:
      - name: post-install-job
        image: bitnami/kubectl
        command: ["/bin/bash","-c"]
        args:
        - |
          i="null"
          while [[ $i != "succeeded" ]]
          do
            i=`kubectl get stacks.pulumi.com -n pulumi-operator {{ printf "%s-%s" .Release.Namespace $serviceName | trunc 63 | trimSuffix "-" }} -o jsonpath='{.status.lastUpdate.state}'`
            echo $i
            sleep 5
          done