---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "pulumi-stack.fullname" . }}-wait-stack"
  namespace: pulumi-operator
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  labels:
    {{- include "pulumi-stack.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: "{{ include "pulumi-stack.fullname" . }}-wait-stack"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "pulumi-stack.fullname" . }}-wait-stack"