apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: {{ .Release.Name }}-cr-whook
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "pr-preview.labels" . | nindent 4 }}
spec:
  taskRef:
    name: create-webhook-{{ .Release.Name }}
  params:
  - name: GitHubOrg
    value: {{ .Values.GithubOrganization }}
  - name: GitHubUser
    value: "iancoffey"
  - name: GitHubRepo
    value: {{ .Values.GithubRepo }}
  {{- if .Values.GithubOrganization  }}
  - name: GithubOrg
    value: {{ .Values.GithubOrganization }}
  {{- else }}
  - name: GithubUser
    value: {{ .Values.GithubUsername }}
  {{- end }}
  - name: GitHubAccessToken
    value: {{ .Values.GithubWebhookToken }}
  - name: ExternalDomain
    value: {{ .Release.Name }}.{{ .Release.Namespace }}.demo.stack.io
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook