apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: {{ .Release.Name }}-show-readme
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "pr-preview.labels" . | nindent 4 }}
spec:
  description: Read and display README file.
  workspaces:
    - name: source
  steps:
    - computeResources: {}
      image: alpine:latest
      name: read
      script: |
        #!/usr/bin/env sh
        cat $(workspaces.source.path)/README.md    
