apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webhook-secret
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "pr-preview.labels" . | nindent 4 }}
stringData:
  token: github-token
  secret: random-string-data