apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-whook-secret
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "pr-preview.labels" . | nindent 4 }}
stringData:
  secret: {{ .Release.Name }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-git-cred
  annotations:
    tekton.dev/git-0: https://github.com
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "pr-preview.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData: 
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://{{ .Values.GithubUsername }}:{{ .Values.GithubReadToken }}@github.com
    