apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ .Release.Name }}-tt
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "pr-preview.labels" . | nindent 4 }}
spec:
  params:
    - name: git-revision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: git-branch
      description: Branch of git that it is running on
    - name: pr-number
      description: number of the pr
    - name: pr-action
      description: action of the pr
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pr-preview-{{ .Release.Name }}-
      spec:
        pipelineRef:
          name: {{ .Release.Name }}-pipeline
        podTemplate:
          securityContext:
            fsGroup: 65532
        params:
        - name: git-revision
          value: $(tt.params.git-revision)
        - name: repo-url
          value: $(tt.params.gitrepositoryurl)
        - name: pr-number
          value: $(tt.params.pr-number)
        - name: pr-action
          value: $(tt.params.pr-action)
        workspaces:
        - name: shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: git-credentials
          secret:
            secretName: {{ .Release.Name }}-git-cred
