apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "epinio-truncate" .Values.epinio.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "epinio-application.labels" . | nindent 4 }}
  annotations:
    {{- include "epinio-application.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.epinio.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.epinio.appName | quote }}
  template:
    metadata:
      annotations:
        app.kubernetes.io/name: {{ .Values.epinio.appName | quote }}
        {{- include "epinio-application.annotations" . | nindent 8 }}
        {{- with .Values.epinio.start }}
        epinio.io/start: {{ . | quote }}
        {{- end }}
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: {{ printf "%s-%s" .Release.Namespace "default"  | quote }}
        vault.hashicorp.com/tls-skip-verify: 'true'
        {{- with .Values.epinio.configpaths }}
        {{- range . }}
        {{- if (contains "vault" .name) }}
        vault.hashicorp.com/agent-inject-template-{{ .path }}: |
          {{`{{- with secret `}} {{ printf "kvv2/data/%s/%s" $.Release.Namespace .path | quote }} {{` }}
          {{- range $k, $v := .Data.data }}
          {{ $k }}="{{ $v }}"
          {{- end }}
          {{- end }}`}}
        {{- end }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "epinio-application.labels" . | nindent 8 }}
        epinio.io/stage-id: {{ .Values.epinio.stageID | quote }}
        epinio.io/app-container: {{ include "epinio-truncate" .Values.epinio.appName }}
    spec:
      serviceAccount: {{ .Release.Namespace }}
      serviceAccountName: {{ .Release.Namespace }}
      automountServiceAccountToken: true
      {{- with .Values.epinio.configurations }}
      volumes:
      {{- range . }}
      - name: {{ . }}
        secret:
          defaultMode: 420
          secretName: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ include "epinio-truncate" .Values.epinio.appName }}
        ports:
        - containerPort: {{ include "epinio-app-listening-port" . }}
          protocol: TCP
        {{- with .Values.epinio.configpaths }}
        volumeMounts:
        {{- range . }}
        - mountPath: /configurations/{{ .path }}
          name: {{ .name }}
          readOnly: true
        {{- end }}
        {{- end }}
        env:
        - name: PORT
          value: {{ include "epinio-app-listening-port" . | quote }}
        {{- range .Values.epinio.env }}
        - name: {{ .name | quote }}
          value: {{ .value | quote }}
        {{- end }}
        {{- with .Values.epinio.configpaths }}
        {{- range . }}
        {{- if contains("psql-conn") . }}
        - name: PSQL_CONNECTION_HOST
          valueFrom:
            secretKeyRef:
              name: {{ . }}
              key: endpoint
        - name: PSQL_CONNECTION_USER
          valueFrom:
            secretKeyRef:
              name: {{ . }}
              key: username
        - name: PSQL_CONNECTION_PORT
          valueFrom:
            secretKeyRef:
              name: {{ . }}
              key: port
        - name: PSQL_CONNECTION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ . }}
              key: password
        {{- end }}
        {{- end }}
        {{- end }}
        image: {{ .Values.epinio.imageURL }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ default "100m" .Values.userConfig.cpu }}
            memory: {{ default "128Mi" .Values.userConfig.memory }}
          requests:
            cpu: {{ default "100m" .Values.userConfig.cpu }}
            memory: {{ default "128Mi" .Values.userConfig.memory }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
