apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  name: {{ include "postgresql.fullname" . }}
  annotations:
    {{- toYaml .Values.crossplanePostgresql.annotations | nindent 4 }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  deletionPolicy: {{ .Values.crossplanePostgresql.deletionPolicy | default "Delete" }}
  forProvider: {}
  providerConfigRef:
    name: {{ .Values.crossplanePostgresql.providerConfigRef | default "default" }}