apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Role
metadata:
  name: {{ include "epinio.ServiceName" . }}
  annotations:
    {{- toYaml .Values.crossplanePostgresql.annotations | nindent 4 }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  deletionPolicy: {{ .Values.crossplanePostgresql.deletionPolicy | default "Delete" }}
  forProvider:
    connectionLimit: 10
    privileges:
      login: true
  writeConnectionSecretToRef:
    name: {{ include "epinio.ServiceName" . }}-psql-conn
    namespace: {{ .Release.Namespace }}
  providerConfigRef:
    name: {{ .Values.crossplanePostgresql.providerConfigRef | default "default" }}

