apiVersion: v1
kind: Secret
data: {}
type: connection.crossplane.io/v1alpha1
metadata:
  annotations:
    {{- toYaml .Values.crossplanePostgresql.annotations | nindent 4 }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }} 
    {{- end }}
    {{- include "postgresql.labels" . | nindent 4 }}
    {{- if .Values.epinio }}
    epinio.io/configuration: "true"
    epinio.io/configuration-origin: {{ .Values.epinio.serviceName }}
    epinio.io/configuration-type: service
    {{- end }}
  name: {{ include "epinio.ServiceName" . }}-psql-conn
  namespace: {{ .Release.Namespace }}
