name: Release Installer

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag for the container image"
        required: true
        default: "v0.0.1-19-dev"

permissions:
  contents: write
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-installer
          tags: |
            ghcr.io/epinio/epinio-installer:latest
            ghcr.io/epinio/epinio-installer:${{ github.event.inputs.tag }}
          push: true
